@extends('errors.layout')
@section('code', __('401'))
@section('title', __('Unauthorized'))
@section('header', __('Unauthorized.'))
@section('message', __('Please try logging in to access this page.'))
