@extends('errors.layout')
@section('code', __('403'))
@section('title', __('Forbidden'))
@section('header', __('Forbidden.'))
@section('message', __('Sorry, the page you are trying to access is off limits.'))
