@extends('errors.layout')
@section('code', '429')
@section('title', __('Too Many Requests'))
@section('header', __('Too many requests.'))
@section('message', __('Woah, slow down there. Please wait a minute before accessing this page again.'))
