@extends('errors.layout')
@section('code', '500')
@section('title', __('Server Error'))
@section('header', __('Server error.'))
@section('message', __('Oops. We did not expect that to happen. Please try again.'))
