version: "2"

checks:
  method-lines:
    config:
      threshold: 50
  similar-code:
    enabled: false

plugins:
  eslint:
    enabled: true

exclude_patterns:
  - "bootstrap/"
  - "config/"
  - "database/migrations/"
  - "docker/"
  - "nova-components/"
  - "operations/"
  - "php/"
  - "public/"
  - "storage/"