<?php

return [
    'roles' => [
        'Admin' => 'Has permission to perform any action on the platform.',
        'User' => 'Has permission to view all necessary records only pertaining to the user.',
    ],
    'guards' => [
        'web',
    ],
    'default' => [
        'User' => [
            'create:submission',
            'view:user',
        ],
    ],
    'permissions' => [
        'view:announcement' => 'Can view an announcement',
        'create:announcement' => 'Can create an announcement',
        'update:announcement' => 'Can update an announcement',
        'delete:announcement' => 'Can delete an announcement',
        'view:award' => 'Can view an award',
        'create:award' => 'Can create an award',
        'update:award' => 'Can update an award',
        'delete:award' => 'Can delete an award',
        'view:document' => 'Can view a document',
        'create:document' => 'Can create a document',
        'update:document' => 'Can update a document',
        'delete:document' => 'Can delete a document',
        'view:position' => 'Can view a position',
        'create:position' => 'Can create a position',
        'update:position' => 'Can update a position',
        'delete:position' => 'Can delete a position',
        'view:qualification' => 'Can view a qualification',
        'create:qualification' => 'Can create a qualification',
        'update:qualification' => 'Can update a qualification',
        'delete:qualification' => 'Can delete a qualification',
        'view:rank' => 'Can view a rank',
        'create:rank' => 'Can create a rank',
        'update:rank' => 'Can update a rank',
        'delete:rank' => 'Can delete a rank',
        'view:specialty' => 'Can view a specialty',
        'create:specialty' => 'Can create a specialty',
        'update:specialty' => 'Can update a specialty',
        'delete:specialty' => 'Can delete a specialty',
        'view:status' => 'Can view a status',
        'create:status' => 'Can create a status',
        'update:status' => 'Can update a status',
        'delete:status' => 'Can delete a status',
        'view:unit' => 'Can view a unit',
        'create:unit' => 'Can create a unit',
        'update:unit' => 'Can update a unit',
        'delete:unit' => 'Can delete a unit',
        'view:form' => 'Can view a form',
        'create:form' => 'Can create a form',
        'update:form' => 'Can update a form',
        'delete:form' => 'Can delete a form',
        'view:field' => 'Can view a custom field',
        'create:field' => 'Can create a custom field',
        'update:field' => 'Can update a custom field',
        'delete:field' => 'Can delete a custom field',
        'view:submission' => 'Can view a form submission',
        'create:submission' => 'Can create a form submission',
        'update:submission' => 'Can update a form submission',
        'delete:submission' => 'Can delete a form submission',
        'view:user' => 'Can view a user',
        'create:user' => 'Can create a user',
        'update:user' => 'Can update a user',
        'note:user' => 'Can update a user\'s note',
        'delete:user' => 'Can delete a user',
        'impersonate:user' => 'Can impersonate a user',
        'view:permission' => 'Can view a permission',
        'create:permission' => 'Can create a permission',
        'update:permission' => 'Can update a permission',
        'delete:permission' => 'Can delete a permission',
        'view:role' => 'Can view a role',
        'create:role' => 'Can create a role',
        'update:role' => 'Can update a role',
        'delete:role' => 'Can delete a role',
        'view:awardrecord' => 'Can view an award record',
        'create:awardrecord' => 'Can create an award record',
        'update:awardrecord' => 'Can update an award record',
        'delete:awardrecord' => 'Can delete an award record',
        'view:assignmentrecord' => 'Can view an assignment record',
        'create:assignmentrecord' => 'Can create an assignment record',
        'update:assignmentrecord' => 'Can update an assignment record',
        'delete:assignmentrecord' => 'Can delete an assignment record',
        'view:combatrecord' => 'Can view a combat record',
        'create:combatrecord' => 'Can create a combat record',
        'update:combatrecord' => 'Can update a combat record',
        'delete:combatrecord' => 'Can delete a combat record',
        'view:qualificationrecord' => 'Can view a qualification record',
        'create:qualificationrecord' => 'Can create a qualification record',
        'update:qualificationrecord' => 'Can update a qualification record',
        'delete:qualificationrecord' => 'Can delete a qualification record',
        'view:rankrecord' => 'Can view a rank record',
        'create:rankrecord' => 'Can create a rank record',
        'update:rankrecord' => 'Can update a rank record',
        'delete:rankrecord' => 'Can delete a rank record',
        'view:servicerecord' => 'Can view a service record',
        'create:servicerecord' => 'Can create a service record',
        'update:servicerecord' => 'Can update a service record',
        'delete:servicerecord' => 'Can delete a service record',
        'view:statusrecord' => 'Can view a status record',
        'create:statusrecord' => 'Can create a status record',
        'update:statusrecord' => 'Can update a status record',
        'delete:statusrecord' => 'Can delete a status record',
        'view:task' => 'Can view a task',
        'create:task' => 'Can create a task',
        'update:task' => 'Can update a task',
        'delete:task' => 'Can delete a task',
        'view:log' => 'Can view application logs',
        'create:attachment' => 'Can create an attachment',
        'create:image' => 'Can create an image',
        'manage:billing' => 'Can manage billing and subscription',
        'manage:api' => 'Can manage API keys and external applications',
        'access:widget' => 'Can access the widget API endpoint',
    ],
];
