<?php

return [
	'roles' => [
		'Admin' => 'Has permission to perform any action on the platform.'
	],
	'permissions' => [
		'view:award' => 'Can view an award',
		'create:award' => 'Can create an award',
		'update:award' => 'Can update an award',
		'delete:award' => 'Can delete an award',
		'view:document' => 'Can view a document',
		'create:document' => 'Can create a document',
		'update:document' => 'Can update a document',
		'delete:document' => 'Can delete a document',
		'view:position' => 'Can view a position',
		'create:position' => 'Can create a position',
		'update:position' => 'Can update a position',
		'delete:position' => 'Can delete a position',
		'view:qualification' => 'Can view a qualification',
		'create:qualification' => 'Can create a qualification',
		'update:qualification' => 'Can update a qualification',
		'delete:qualification' => 'Can delete a qualification',
		'view:rank' => 'Can view a rank',
		'create:rank' => 'Can create a rank',
		'update:rank' => 'Can update a rank',
		'delete:rank' => 'Can delete a rank',
		'view:specialty' => 'Can view a specialty',
		'create:specialty' => 'Can create a specialty',
		'update:specialty' => 'Can update a specialty',
		'delete:specialty' => 'Can delete a specialty',
		'view:status' => 'Can view a status',
		'create:status' => 'Can create a status',
		'update:status' => 'Can update a status',
		'delete:status' => 'Can delete a status',
		'view:unit' => 'Can view a unit',
		'create:unit' => 'Can create a unit',
		'update:unit' => 'Can update a unit',
		'delete:unit' => 'Can delete a unit',
		'view:form' => 'Can view a form',
		'create:form' => 'Can create a form',
		'update:form' => 'Can update a form',
		'delete:form' => 'Can delete a form',
		'view:soldier' => 'Can view a soldier',
		'create:soldier' => 'Can create a soldier',
		'update:soldier' => 'Can update a soldier',
		'delete:soldier' => 'Can delete a soldier',
		'view:user' => 'Can view a user',
		'create:user' => 'Can create a user',
		'update:user' => 'Can update a user',
		'delete:user' => 'Can delete a user',
		'view:permission' => 'Can view a permission',
		'create:permission' => 'Can create a permission',
		'update:permission' => 'Can update a permission',
		'delete:permission' => 'Can delete a permission',
		'view:role' => 'Can view a role',
		'create:role' => 'Can create a role',
		'update:role' => 'Can update a role',
		'delete:role' => 'Can delete a role',
	]
];