<?php

declare(strict_types=1);

use App\Http\Middleware\InitializeTenancyBySubdomain;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth', InitializeTenancyBySubdomain::class],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    'brand' => [
        'logo' => realpath(__DIR__.'/../public/svg/logo.svg'),
        'color' => 'bg-blue-600',
    ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Spark Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Spark to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        Features::mustAcceptTerms(),
        // Features::euVatCollection(['home-country' => 'BE']),
        Features::invoiceEmails(['custom-addresses' => true]),
        Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Invoice Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF invoices generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'invoice_data' => [
        'vendor' => 'Deschutes Design Group LLC',
        'product' => 'PERSCOM Personnel Management System',
        'street' => '13507 SW Shumway Rd',
        'location' => 'Powell Butte, Oregon',
        'phone' => '541-213-9729',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [
        'tenant' => [
            'model' => App\Models\Tenant::class,
            'trial_days' => 7,
            'default_interval' => 'monthly',
            'plans' => [
                [
                    'name' => 'Basic',
                    'short_description' => 'For small organizations who need core personnel management services without the need to share and exchange personnel data.',
                    'monthly_id' => env('STRIPE_PRODUCT_BASIC_MONTH'),
                    'yearly_id' => env('STRIPE_PRODUCT_BASIC_YEAR'),
                    'features' => [
                        'All core features',
                        'Social login support',
                        'Application provided subdomain',
                        'Community support',
                    ],
                    'options' => [
                        App\Features\SocialLoginFeature::class,
                    ],
                ],
                [
                    'name' => 'Pro',
                    'short_description' => 'For growing organizations who wish to integrate their personnel data into third-party services without enterprise level complexity.',
                    'monthly_id' => env('STRIPE_PRODUCT_PRO_MONTH'),
                    'yearly_id' => env('STRIPE_PRODUCT_PRO_YEAR'),
                    'features' => [
                        'Access to powerful API',
                        'Widgets and website integration',
                        'Custom subdomain',
                        'Ticket and email support',
                    ],
                    'options' => [
                        App\Features\SocialLoginFeature::class,
                        App\Features\ApiAccessFeature::class,
                        App\Features\CustomSubDomainFeature::class,
                        App\Features\SupportTicketFeature::class,
                    ],
                ],
                [
                    'name' => 'Enterprise',
                    'short_description' => 'For large organizations that rely on powerful personnel management solutions and require personnel data communication between essential business services.',
                    'monthly_id' => env('STRIPE_PRODUCT_ENTERPRISE_MONTH'),
                    'yearly_id' => env('STRIPE_PRODUCT_ENTERPRISE_YEAR'),
                    'features' => [
                        'Export and backup personnel data',
                        'Webhooks and real-time app notifications',
                        'Single sign-on integration',
                        'Priority support',
                    ],
                    'options' => [
                        App\Features\SocialLoginFeature::class,
                        App\Features\ApiAccessFeature::class,
                        App\Features\CustomSubDomainFeature::class,
                        App\Features\SupportTicketFeature::class,
                        App\Features\CustomDomainFeature::class,
                        App\Features\ExportDataFeature::class,
                        App\Features\OAuth2AccessFeature::class,
                        App\Features\SingleSignOnFeature::class,
                        App\Features\WebhookFeature::class,
                    ],
                ],
            ],
        ],
    ],
];
