<?php

declare(strict_types=1);

namespace App\Filament\App\Pages\Auth;

use App\Data\ManagedNotification;
use App\Models\Enums\NotificationChannel;
use App\Models\Enums\NotificationGroup;
use App\Services\NotificationService;
use App\Settings\UserSettings;
use Filament\Forms\Components\CheckboxList;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Pages\Auth\EditProfile as BaseEditProfile;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;

class EditProfile extends BaseEditProfile
{
    public function form(Form $form): Form
    {
        $notifications = NotificationService::configurableNotifications();

        return $form
            ->schema([
                Tabs::make()
                    ->tabs([
                        Tabs\Tab::make('Profile')
                            ->icon('heroicon-o-user')
                            ->schema([
                                $this->getNameFormComponent(),
                                $this->getEmailFormComponent(),
                                TextInput::make('phone_number')
                                    ->nullable()
                                    ->tel()
                                    ->helperText('By providing your phone number, you consent to allow Deschutes Design Group LLC/PERSCOM to send you account-related text messages. Alert and data rates may apply. You may configure your notification settings at anytime by clicking the "Notifications" tab above.'),
                                $this->getPasswordFormComponent(),
                                $this->getPasswordConfirmationFormComponent(),
                            ]),
                        Tabs\Tab::make('Notifications')
                            ->icon('heroicon-o-bell')
                            ->schema($notifications->map(function (Collection $notifications, $group) {
                                $group = NotificationGroup::from($group);

                                return Section::make($group->getLabel())
                                    ->description($group->getDescription())
                                    ->icon($group->getIcon())
                                    ->schema($notifications->map(function (ManagedNotification $notification) {
                                        return CheckboxList::make("notifications.$notification->notificationClass")
                                            ->label($notification->title)
                                            //->helperText($notification->description)
                                            ->columns(5)
                                            ->gridDirection('row')
                                            ->bulkToggleable()
                                            ->options(NotificationChannel::class);
                                    })->toArray());
                            })->toArray()),
                        Tabs\Tab::make('Social')
                            ->icon('heroicon-o-device-phone-mobile')
                            ->schema([
                                TextInput::make('discord_user_id')
                                    ->label('Discord User ID')
                                    ->helperText('Your Discord User ID. This should be your Discord snowflake ID - not your username or display name.'),
                            ]),
                    ]),
            ]);
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $settings = app(UserSettings::class);

        return parent::mutateFormDataBeforeFill(array_merge($data, [
            'notifications' => data_get($settings->notifications, Auth::user()->getAuthIdentifier()),
        ]));
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $settings = app(UserSettings::class);
        $settings->notifications = [
            Auth::user()->getAuthIdentifier() => data_get($data, 'notifications'),
        ];
        $settings->save();

        data_forget($data, 'notifications');

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
